[tox]
envlist = py310,py311,py312,py313,py314
minversion = 4.0

[testenv]
description = run pytest with {basepython}
runner = uv-venv-runner
uv_python_preference = managed
package = editable
deps =
    pytest
commands =
    pytest {posargs}
